load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//components:__subpackages__"])

cc_library(
    name = "proto_matcher",
    testonly = 1,
    hdrs = ["proto_matcher.h"],
    deps = [
        "@com_google_googletest//:gtest",
    ],
)
