#!/usr/bin/env bash
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run this to push sqs lambda image to AWS Elastic Container Registry

set -o errexit
set -o xtrace

if [[ -z "${AWS_ECR}" ]]; then
      echo "Please export AWS_ECR address as suggested by AWS Elastic Container Registry"
      echo "This can be found in 'View Push Commands'"
      echo "in the form of 123456789.dkr.ecr.us-east-1.amazonaws.com'"
fi

aws ecr get-login-password --region us-east-1 |
  docker login --username AWS --password-stdin ${AWS_ECR}

WORKSPACE=$(git rev-parse --show-toplevel)
DIST_DIR="${WORKSPACE}"/dist
unzip -cq "${DIST_DIR}"/aws_artifacts.zip sqs_lambda.tar | docker load -i /dev/stdin
AWS_IMAGE_URI="${AWS_ECR}"/sqs_lambda:latest
docker tag bazel/components/aws:sqs_lambda "${AWS_IMAGE_URI}"
docker push "${AWS_IMAGE_URI}"
