#!/bin/bash
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# helper script to run commit-and-tag-version tool.
# More info at https://github.com/absolute-version/commit-and-tag-version/
#
# environment variables (all optional):
#   WORKSPACE             Absolute path to the bazel repo root

set -o errexit

RELEASE_TOOLS_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
readonly RELEASE_TOOLS_DIR
readonly TOOLS_DIR="${RELEASE_TOOLS_DIR}"/../../builders/tools

"${TOOLS_DIR}"/commit-and-tag-version "$@"
