#!/bin/bash

set -o pipefail
set -o errexit

BAZEL_PATH=/usr/bin

usage() {
  local exitval=${1-1}
  cat >&2 << USAGE
usage:
  $0 <options>
    --verbose                     Emit verbose info. Default: false
USAGE
  # shellcheck disable=SC2086
  exit ${exitval}
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --verbose)
      set -o xtrace
      shift
      ;;
    -h | --help) usage 0 ;;
    *) usage ;;
  esac
done

function install_bazelisk() {
  go install github.com/bazelbuild/bazelisk@v1.19.0
  BAZELISK="$(go env GOPATH)"/bin/bazelisk
  if [[ -n ${BAZEL_PATH} ]] && [[ -d ${BAZEL_PATH} ]]; then
    ln -s "${BAZELISK}" "${BAZEL_PATH}"/bazel
  fi
  # install the specified version of bazel
  USE_BAZEL_VERSION="$(cat /scripts/.bazelversion)"
  export USE_BAZEL_VERSION
  "${BAZELISK}" version
  rm -rf /bazel_root/*
}

function cleanup() {
  cd /
  go clean -cache -modcache
}

install_bazelisk
cleanup
