#!/bin/bash

set -o pipefail
set -o errexit

VERBOSE=0

usage() {
  local exitval=${1-1}
  cat >&2 << USAGE
usage:
  $0 <options>
    --verbose                     Emit verbose info. Default: false
USAGE
  # shellcheck disable=SC2086
  exit ${exitval}
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --verbose)
      VERBOSE=1
      shift
      ;;
    -h | --help)
      usage 0
      break
      ;;
    *)
      usage
      break
      ;;
  esac
done

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
readonly SCRIPT_DIR
# shellcheck disable=SC1090
. "${SCRIPT_DIR}"/install_go.sh

function yum_update() {
  yum -y update
}

function install_compilers() {
  amazon-linux-extras install -y \
    python3.8 \
    java-openjdk11
  yum install -y java-11-openjdk-devel-11.0.16.0.8-1.amzn2.0.1
  mkdir -p /opt/bin
  update-alternatives --install /opt/bin/python3 python3 /usr/bin/python3.8 100
}

function install_nitro() {
  amazon-linux-extras install -y aws-nitro-enclaves-cli
  yum install -y aws-nitro-enclaves-cli-devel
}

function install_gcc() {
  # install gcc, which is required to build socat
  yum install -y gcc-7.3.1-15.amzn2
}

function install_misc() {
  yum install -y \
    gettext-0.19.8.1-3.amzn2 \
    git-2.37.1-1.amzn2.0.1 \
    tar-1.26-35.amzn2 \
    unzip-6.0-43.amzn2 \
    zip-3.0-11.amzn2.0.2
}

function install_packer() {
  yum install -y yum-utils-1.1.31-46.amzn2.0.1.noarch
  yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  yum -y install packer-1.8.4-1
  update-alternatives --install /usr/local/bin/packer packer /usr/bin/packer 100

  /usr/local/bin/packer version
}

function install_clang() {
  yum install -y clang-11.1.0-1.amzn2.0.2
  clang --version
}

if [[ ${VERBOSE} -eq 1 ]]; then
  printf "=== SHELL ENVIRONMENT ===\n"
  env
fi

yum_update
install_compilers
install_nitro
install_misc
install_clang
install_golang "${BUILD_ARCH}"
install_gcc
install_packer
