#!/bin/bash

set -o pipefail
set -o errexit

VERBOSE=0

usage() {
  local exitval=${1-1}
  cat >&2 << USAGE
usage:
  $0 <options>
    --verbose                     Emit verbose info. Default: false
USAGE
  # shellcheck disable=SC2086
  exit ${exitval}
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --verbose)
      VERBOSE=1
      shift
      ;;
    -h | --help) usage 0 ;;
    *) usage ;;
  esac
done

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
readonly SCRIPT_DIR
# shellcheck disable=SC1090
. "${SCRIPT_DIR}"/install_go.sh

function yum_update() {
  yum -y update
}

function install_python() {
  amazon-linux-extras install -y \
    python3.8
  mkdir -p /opt/bin
  update-alternatives \
    --install /opt/bin/python3 python3-opt /usr/bin/python3.8 100 \
    --slave /opt/bin/python python /usr/bin/python3.8

}

function install_nitro() {
  amazon-linux-extras install -y aws-nitro-enclaves-cli
  yum install -y aws-nitro-enclaves-cli-devel
}

function install_gcc() {
  # install gcc, which is required to build socat
  yum install -y "gcc-7.3.1*"
}

function install_misc() {
  yum install -y \
    "gettext-0.19.8.*" \
    "git-2.38*" \
    "tar-1.26*" \
    "unzip-6.0*" \
    "which-2.*" \
    "zip-3.0*"
}

function install_packer() {
  yum install -y "yum-utils-1.1.31*"
  yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  yum -y install "packer-1.9.1*"
  update-alternatives --install /usr/local/bin/packer packer /usr/bin/packer 100

  /usr/local/bin/packer version
}

function install_clang() {
  yum install -y "clang-11.1.0*"
  clang --version
}

function cleanup() {
  cd /
  go clean -cache -modcache
}

if [[ ${VERBOSE} -eq 1 ]]; then
  printf "=== SHELL ENVIRONMENT ===\n"
  env
fi

yum_update
install_nitro
install_misc
install_clang
install_golang "${BUILD_ARCH}"
install_gcc
install_packer
install_python
cleanup
