#!/bin/sh

npm install --global commit-and-tag-version

# Install the GitHub CLI tool (https://cli.github.com/)
apk add github-cli

GOBIN=/usr/local/go/bin go install github.com/bazelbuild/buildtools/buildozer@5.1.0
