#!/bin/bash
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit

WORKSPACE=$(bazel info workspace)
IMAGE_TAGGED=builders/release:release_image

# as needed, build release container image and load it into the local docker client
if ! docker image inspect bazel/${IMAGE_TAGGED} >/dev/null 2>&1; then
  bazel run //${IMAGE_TAGGED}
fi

# TODO: this script likely needs to be generalized to support other github repos
REPO='https://github.com/privacysandbox/fledge-key-value-service'
GH_TOKEN="$(cat ~/.gh_token)"
GLOBAL_OPTS="--repo-url ${REPO} --token=${GH_TOKEN}"

docker run -it --rm \
  --entrypoint=/bin/bash \
  -v "${WORKSPACE}:/src/workspace" \
  -w /src/workspace \
  bazel/${IMAGE_TAGGED} \
  -c "release-please ${GLOBAL_OPTS} $*"
