#!/bin/sh

set -o errexit

function install_packages() {
  apk --no-cache add \
    bash=5.2.15-r0 \
    curl=7.87.0-r0 \
    jq=1.6-r2
}

function install_ghz() {
  go install github.com/bojand/ghz/cmd/ghz@v0.111.0
  ghz --help
}

install_packages
install_ghz
