#!/bin/bash
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o xtrace

IMAGE_TAGGED=builders/bazel:bazel_build_image
WORKSPACE=$(bazel info workspace)

# build container image and load it into the local docker client
bazel run //${IMAGE_TAGGED}

docker run -it --rm \
  --entrypoint=/bin/bash \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "${HOME}/.cache/bazel:/root/.cache/bazel" \
  -v "${WORKSPACE}:/src/workspace" \
  -w /src/workspace \
  --env AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
  --env AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
  bazel/${IMAGE_TAGGED} \
  "$@"
