#!/bin/bash

set -o pipefail
set -o errexit
set -o xtrace

SCRIPT_DIR="$(dirname $(readlink -f $0))"

VE_DIR=/usr/pre-commit-venv
python3 -m venv ${VE_DIR}
ls -lRh ${SCRIPT_DIR}
${VE_DIR}/bin/pip install pre-commit
${VE_DIR}/bin/pre-commit help

# initialize pre-commit cache, which needs a git repo (a temporary will suffice)
GIT_REPO=$(mktemp -d)
git init ${GIT_REPO}
cd ${GIT_REPO}
# create a placeholder terraform file in the git repo, giving addlicense something to do
echo "# a placeholder file for addlicense" > placeholder.tf
git add placeholder.tf
# run a single arbitrary hook to trigger population of cache
${VE_DIR}/bin/pre-commit run --config ${SCRIPT_DIR}/.pre-commit-config.yaml || true
rm -rf ${GIT_REPO}
ls -lh ${PRE_COMMIT_HOME}
