#!/bin/bash

set -o pipefail
set -o errexit

VERBOSE=0

usage() {
  local exitval=${1-1}
  cat >&2 << USAGE
usage:
  $0 <options>
    --verbose                     Emit verbose info. Default: false
USAGE
  # shellcheck disable=SC2086
  exit ${exitval}
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --verbose)
      VERBOSE=1
      shift
      ;;
    -h | --help)
      usage 0
      break
      ;;
    *)
      usage
      break
      ;;
  esac
done

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
readonly SCRIPT_DIR
# shellcheck disable=SC1090
. "${SCRIPT_DIR}"/install_go.sh

function yum_update() {
  yum -y update
}

function install_python() {
  amazon-linux-extras install -y python3.8
  update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 100
}

function install_nitro() {
  amazon-linux-extras install -y aws-nitro-enclaves-cli
  yum install -y aws-nitro-enclaves-cli-devel tar
}

function install_gcc() {
  # install gcc, which is required to build socat
  yum install -y gcc-7.3.1-15.amzn2
}

function install_misc() {
  yum install -y unzip zip
}

function install_packer() {
  yum install -y yum-utils
  yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  yum -y install packer
  update-alternatives --install /usr/local/bin/packer packer /usr/bin/packer 100

  /usr/local/bin/packer version
}

function install_clang() {
  yum install -y clang-11.1.0-1.amzn2.0.2

  clang --version
}

if [[ ${VERBOSE} -eq 1 ]]; then
  printf "=== SHELL ENVIRONMENT ===\n"
  env
fi

function get_arch() {
  declare -r _MACHINE=$(uname -m)
  declare -r -A _MACHINE2ARCH=(
    [x86_64]="amd64"
    [aarch64]="arm64"
  )
  declare -r _ARCH=${_MACHINE2ARCH[${_MACHINE}]}
  if [[ -z $_ARCH ]]; then
    printf "Unrecognized or unsupported machine/architecture: %s\n" "${_MACHINE}" &>/dev/stderr
    exit 1
  fi
  printf "%s\n" "${_ARCH}"
}

ARCH=$(get_arch)
readonly ARCH

yum_update
install_python
install_nitro
install_misc
install_clang
install_golang "${ARCH}"
install_gcc
install_packer
