#!/usr/bin/env bash

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# environment variables exported to AWS CLI
# For more info on supported env vars, see:
#   https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
#
#     AWS_ACCESS_KEY_ID
#     AWS_DEFAULT_REGION
#     AWS_SECRET_ACCESS_KEY

declare -a ENV_VARS
ENV_VARS+=(
  "AWS_ACCESS_KEY_ID"
  "AWS_DEFAULT_REGION"
  "AWS_SECRET_ACCESS_KEY"
)

declare -a DOCKER_RUN_ARGS
DOCKER_RUN_ARGS+=(
  "--rm"
)
for evar in "${ENV_VARS[@]}"
do
  DOCKER_RUN_ARGS+=(
    "--env ${evar}"
  )
done
if [[ -t 0 ]] && [[ -t 1 ]]; then
  # stdin and stdout are open, assume it's an interactive tty session
  DOCKER_RUN_ARGS+=(
    "--interactive"
    "--tty"
  )
fi

# shellcheck disable=SC2068
docker run \
    ${DOCKER_RUN_ARGS[@]} \
    amazon/aws-cli -- "$@"
