#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

TMPDIR="$(mktemp --directory)"
trap 'rm -rf "${TMPDIR}"' EXIT
{
  cat <<EOF
FROM golang:1.23.4-bookworm as build
RUN git clone --depth=1 --branch=v1.19.3 https://github.com/GoogleContainerTools/container-structure-test.git /tmp/cst \
  && cd /tmp/cst \
  && go build ./cmd/container-structure-test

FROM scratch
COPY --from=build /tmp/cst/container-structure-test /
EOF
} | docker buildx build --quiet --file=- --output="${TMPDIR}" .
"${TMPDIR}"/container-structure-test "$@"
