#!/usr/bin/env bash
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Print the CPU architecture

set -o errexit

trap _cleanup EXIT
function _cleanup() {
  local -r -i STATUS=$?
  if [[ ${STATUS} -ne 0 ]]; then
    printf "Error: get-architecture status code: %s\n" "${STATUS}" &>/dev/stderr
  fi
  exit ${STATUS}
}

if [[ -n ${BUILD_ARCH} ]]; then
  printf "%s\n" "${BUILD_ARCH}"
else
  docker run --rm --entrypoint=/usr/bin/dpkg ${DOCKER_REGISTRY}ubuntu:20.04 --print-architecture
fi
