#!/usr/bin/env bash
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# environment variables (all optional):
#   TERRAFORM_VERSION            specify the terraform version to use
#   WORKSPACE                    repo root directory, must be an absolute path
#
# AWS-related environment variables exported into the terraform container:
# For more info on supported env vars, see:
#   https://registry.terraform.io/providers/hashicorp/aws/latest/docs#environment-variables
#
#     AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY
#     AWS_SESSION_TOKEN
#     AWS_REGION
#     AWS_DEFAULT_REGION
#     AWS_PROFILE

set -o errexit

# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/builder.sh

if ! [[ -v TERRAFORM_VERSION ]]; then
  TERRAFORM_VERSION=1.0.4
fi

declare -a ENV_VARS
builder::add_aws_env_vars ENV_VARS
ENV_VARS+=(
  "HOME=/home"
)

declare -a DOCKER_RUN_ARGS=(
  "--rm"
)
for evar in "${ENV_VARS[@]}"
do
  DOCKER_RUN_ARGS+=(
    "--env=${evar}"
  )
done
if [[ -t 0 ]] && [[ -t 1 ]]; then
  # stdin and stdout are open, assume it's an interactive tty session
  DOCKER_RUN_ARGS+=(
    "--interactive"
    "--tty"
  )
fi

readonly IMAGE_TAGGED=hashicorp/terraform:"${TERRAFORM_VERSION}"
REL_PWD="$(realpath --relative-to="${WORKSPACE}" "$(pwd)")"
readonly REL_PWD
WORKSPACE_MOUNT="$(builder::get_docker_workspace_mount)"
readonly WORKSPACE_MOUNT

if [[ -d ${HOME}/.aws ]]; then
  DOCKER_RUN_ARGS+=("--volume=${HOME}/.aws/:/home/.aws/")
fi
if [[ -d ${HOME}/.config/gcloud ]]; then
  DOCKER_RUN_ARGS+=("--volume=${HOME}/.config/gcloud/:/home/.config/gcloud/")
fi

DOCKER_RUN_ARGS+=(
  "--user=$(id -u):$(id -g)"
  "--volume=${WORKSPACE_MOUNT}:/src/workspace"
  "--workdir=/src/workspace/${REL_PWD}"
)

# shellcheck disable=SC2068
docker run \
  "${DOCKER_RUN_ARGS[@]}" \
  "${IMAGE_TAGGED}" \
  "$@"
