#!/bin/bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
# Install killall, wget, ps, binutils and linux perf.
apt-get update
apt-get install wget psmisc procps binutils linux-tools-generic -y
# Installing graphviz and gperftools requires these ENV variables.
export DEBIAN_FRONTEND=noninteractive
export TZ=Etc/UTC
# Install graphviz and libgperf tools.
apt-get install graphviz libgoogle-perftools-dev -y
# Install pprof.
wget https://go.dev/dl/go1.21.6.linux-amd64.tar.gz
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz && rm go1.21.6.linux-amd64.tar.gz
/usr/local/go/bin/go install github.com/google/pprof@latest
# Create symlink
ln -s /usr/lib/linux-tools/5.4.0-169-generic/perf /usr/local/bin/linux-perf
ln -s /root/go/bin/pprof /usr/local/bin/pprof
# Run the server
/server/bin/server --port=50051 --delta_directory=/data --realtime_directory=/data/realtime --stderrthreshold=0
