#!/usr/bin/env bash

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# environment variables (all optional):
#     WORKSPACE                    Set the path to the workspace (repo root)

set -o pipefail
set -o errexit

trap _cleanup EXIT
function _cleanup() {
  declare -r -i STATUS=$?
  if [[ ${STATUS} -ne 0 ]]; then
    printf "collect-logs exit code: %d\n" ${STATUS} &>/dev/stderr
    sleep 5s
  fi
  exit ${STATUS}
}

ZIP_FILENAME="$1"
if [[ ${ZIP_FILENAME##*.} != zip ]]; then
  ZIP_FILENAME=logs.zip
fi
SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
WORKSPACE="${WORKSPACE-"$(readlink -f "${SCRIPT_DIR}"/..)"}"
TMPDIR="$(mktemp --directory)"
readonly TMPDIR
mkdir -p "${TMPDIR}"/{test,other}
# copy all test.log and test.xml files to the testlogs dir
if [[ -d "${WORKSPACE}"/bazel-testlogs ]]; then
  find -L "${WORKSPACE}"/bazel-testlogs -name test.log -exec cp --parents {} "${TMPDIR}"/test ';'
  find -L "${WORKSPACE}"/bazel-testlogs -name test.xml -exec cp --parents {} "${TMPDIR}"/test ';'
fi
# copy log files under bazel-out (other than test.log) to the buildlogs dir
if [[ -d "${WORKSPACE}"/bazel-out ]]; then
  find -L "${WORKSPACE}"/bazel-out -name "*.log" ! -name "test.log" -exec cp --parents {} "${TMPDIR}"/other ';'
fi
if compgen -G "${TMPDIR}/test/src/workspace/bazel-testlogs/*" &>/dev/null; then
  mv --target-directory="${TMPDIR}"/test "${TMPDIR}"/test/src/workspace/bazel-testlogs/*
  rmdir "${TMPDIR}"/test/{src/workspace/bazel-testlogs,src/workspace,src}
fi

if command -v rename &>/dev/null; then
  # Rename the copied test.log and test.xml files to sponge_log.log and sponge_log.xml
  find -L "${TMPDIR}" -name test.log -exec rename 's/test.log/sponge_log.log/' {} ';'
  find -L "${TMPDIR}" -name test.xml -exec rename 's/test.xml/sponge_log.xml/' {} ';'
fi

declare -r DISTDIR="${WORKSPACE}"/dist
mkdir -p "${DISTDIR}"
(
  cd "${TMPDIR}"
  zip -r -q "${DISTDIR}/${ZIP_FILENAME}" -- *
)
printf "stored bazel logs to %s\n" "${DISTDIR}/${ZIP_FILENAME}" &>/dev/stderr
unzip -Z -h "${DISTDIR}/${ZIP_FILENAME}" &>/dev/stderr
rm -rf "${TMPDIR}"
