#!/bin/bash

# This script will be run bazel when building process starts to
# generate key-value information that represents the status of the
# workspace. The output should be like
#
# KEY1 VALUE1
# KEY2 VALUE2
#
# We want to force binaries to relink when the Git SHA changes. This can be
# done by prefixing keys with "STABLE_". To avoid breaking compatibility with
# other status scripts, this one still echos the non-stable ("volatile") names.

if ! command -v git; then
  exit 0
fi

TOPLEVEL_DIR=$(git rev-parse --show-toplevel)
readonly TOPLEVEL_DIR
VERSION=$(cat "${TOPLEVEL_DIR}"/version.txt)
readonly VERSION

cat <<EOF
STABLE_VERSION ${VERSION}
EOF

if [[ -s /etc/bazel.bazelrc ]]; then
  printf "STABLE_%s\n" "$(grep -o 'TOOLCHAINS_HASH.*$' /etc/bazel.bazelrc | tr '=' ' ')"
fi
