#!/usr/bin/env bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# environment variables supported (all optional):
#     WORKSPACE          Set the path to the workspace (repo root)

set -o pipefail
set -o errexit

WORKSPACE="${WORKSPACE-"$(git rev-parse --show-toplevel)"}"
readonly WORKSPACE
readonly GRPC_CLI=bazel-bin/external/com_github_grpc_grpc/test/cpp/util/grpc_cli

if ! [[ -s ${GRPC_CLI} ]]; then
  printf "Building grpc_cli\n"
  "${WORKSPACE}"/builders/tools/bazel-debian build //tools:grpc_cli
fi

"${GRPC_CLI}" "$@"
