#!/usr/bin/env bash
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# helper script to build and execute the gh CLI tool.
# Read the gh manual at https://cli.github.com/manual.
#
# environment variables (all optional):
#   WORKSPACE                    repo root directory, must be an absolute path
#   BUILD_WORKSPACE_DIRECTORY    repo root directory, secondary to WORKSPACE

set -o errexit

readonly IMAGE_TAGGED="hashicorp/terraform:1.0.4"
readonly WORKSPACE=${WORKSPACE-${BUILD_WORKSPACE_DIRECTORY-$(bazel info workspace)}}

docker run --rm \
  --volume "${WORKSPACE}:/src/workspace" \
  --workdir /src/workspace \
  ${IMAGE_TAGGED} "$@"
