#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This scirpts generates 3K delta files, each delta files has 100 insertion records.
# All keys are unique.

WORKSPACE="$(git rev-parse --show-toplevel)"
readonly WORKSPACE
readonly DELTAS_DIR=tools/serving_data_generator/deltas
mkdir -p "${WORKSPACE}/${DELTAS_DIR}"
BAZEL_EXTRA_ARGS=

"${WORKSPACE}"/builders/tools/bazel-debian build //tools/serving_data_generator:test_serving_data_generator
"${WORKSPACE}"/builders/tools/normalize-bazel-symlinks

declare -i nanosecond
for _ in {1..3000}
do
  nanosecond=$(date '+%s%N')
  ${WORKSPACE}/bazel-bin/tools/serving_data_generator/test_serving_data_generator \
    --key=${nanosecond} \
    --num_records=100   \
    --timestamp=${nanosecond} \
    --output_dir="${WORKSPACE}/${DELTAS_DIR}"
done
