#!/bin/bash
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o xtrace

# Example command to generate test data.
# Generate test riegeli file with keys "foo" and values "foo_value".
bazel run -c opt //tools/serving_data_generator:test_serving_data_generator -- --output_dir="$(pwd)"

echo "Riegeli file was generated at $(pwd). For finer control of data and outputs, please use test_serving_data_generator.cc directly."
